Presentation/Controllers/Mvc/FileController.cs
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FileManager.BusinessLogic;
using FileManager.Models;


namespace FileManager.Controllers
{
    public class FileController : Controller
    {
        private readonly IFileService service;

        private readonly IStringLocalizer<FileController> localizer;

        public FileController(IFileService logic, IStringLocalizer<FileController> localizer)
        {
            this.service = logic;
            this.localizer = localizer;
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            if (service.TryGetFileDetails(User.Identity.Name, id, out File details))
            {
                ViewData["FileToShow"] = details;
                ViewData["UserName"] = User.Identity.Name;

                return View();
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["NoAuthorization"];
            return View("Error");
        }

        // GET: File/Upload
        [Authorize]
        public ActionResult Upload()
        {
            ViewData["UserName"] = User.Identity.Name;
            return View();
        }

        // POST: File/Upload
        [HttpPost]
        [Authorize]
        public ActionResult Upload(IFormFile file)
        {
            if (service.TryUploadFile(file.FileName, (int)file.Length, User.Identity.Name, file.OpenReadStream()))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["UploadError"];
            return View("Error");
        }

        // GET: File/Download/5
        [Authorize]
        public ActionResult Download(int id)
        {
            if (service.TryDownloadFile(User.Identity.Name, id, out File fileDetails, out System.IO.FileStream stream))
            {
                return File(stream,
                        contentType: $"application/{fileDetails.Extension}",
                        fileDownloadName: $"{fileDetails.Name}.{fileDetails.Extension}");
            }
            
            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["NoAuthorization"];
            return View("Error");
        }

        // GET: File/Delete/5
        [HttpGet]
        [Authorize]
        public ActionResult Delete(int id)
        {
            ViewData["UserName"] = User.Identity.Name;
            ViewData["Id"] = id;

            return View();
        }

        // POST: File/Delete/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            if (service.TryDeleteFile(User.Identity.Name, id))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["NoAuthorization"];
            return View("Error");
        }

        [Authorize]
        public ActionResult Share(int id)
        {
            if (service.TryShareFile(User.Identity.Name, id, out string fileHash))
            {
                string href = $"{Request.Host}/File/{nameof(Shared)}/{fileHash}";
                return Content($"{localizer["Href"]}: {href}");
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["NoAuthorization"];
            return View("Error");
        }
        
        public ActionResult Shared(string hash)
        {
            if (service.AddSharedAuthorized(User.Identity.Name, hash))
            {
                return RedirectToAction("Index", "Home");
            }

            if (service.DownloadSharedAnonymous(hash, out File file, out System.IO.FileStream stream))
            {
                return File(
                    stream,
                    contentType: $"application/{file.Extension}",
                    fileDownloadName: $"{file.Name}.{file.Extension}"
                );
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["AlreadyOwner"];
            return View("Error");
        }
    }
}

Presentation/Controllers/Mvc/UserController.cs
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FileManager.BusinessLogic;


namespace FileManager.Controllers
{
    public class UserController : Controller
    {
        private readonly IStringLocalizer<FileController> localizer;

        private readonly IUserService service;

        public UserController(IUserService logic, IStringLocalizer<FileController> localizer)
        {
            this.service = logic;
            this.localizer = localizer;
        }

        [Authorize]
        public ActionResult Details(string userName)
        {
            var userToShow = service.GetUserByLogin(userName);

            ViewData["UserToShow"] = userToShow;
            ViewData["UserName"] = User.Identity.Name;

            return View();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            ViewData["UserName"] = User.Identity.Name;
            ViewData["Id"] = id;

            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            if (service.TryDeleteUser(User.Identity.Name, id))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["UserName"] = User.Identity.Name;
            ViewData["ErrorMessage"] = localizer["NoAuthorization"];
            return View("Error");
        }
    }
}

Presentation/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileManager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FileManager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>

                    @if (ViewData["UserName"] != null)
                    {
                        <li><a asp-controller="File" asp-action="Upload">@Localizer["Upload"]</a></li>
                    }

                    <li><a asp-area="" asp-controller="Home" asp-action="About">@Localizer["About"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">@Localizer["Contact"]</a></li>

                    @if (ViewData["UserName"] != null)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="Details" asp-route-userName=@ViewData["UserName"]> @ViewData["UserName"] </a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">@Localizer["Logout"]</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />


    <div class="container body-content">

        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            @Localizer["AspNet"]
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            @Localizer["VisualStudio"]
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            @Localizer["Azure"]
                        </p>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FileManager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>